name: compile PR changelog 

on:
    pull_request: 

jobs:
    create-changlog:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

        
            - name: Print PR commits
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                PR_NUMBER=${{ github.event.number }}
                echo "Fetching commits for PR #${PR_NUMBER}"

                # Fetch commits using GitHub API and jq to parse JSON
                curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits" | \
                jq -r '.[] | "Commit SHA: \(.sha)\nAuthor: \(.commit.author.name)\nMessage: \(.commit.message)\n---"'
                            
                

