name: compile PR changelog 

on:
    pull_request: 

jobs:
    create-changlog:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Create changelog
              id: changelog
              uses: dragonraid/changelog-emitter
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Print changelog
              if: steps.changelog.outputs.isEmpty == false
              run: |
                echo "${{ steps.changelog.outputs.changelog }}"
            # - name: Get PR commits
            #   id: commits 
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: |
            #     echo "Fetching commits for PR #${{ github.event.number }}"
                
            #     CHANGELOG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            #     "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/commits" | \
            #     jq -r '.[] | "Commit SHA: \(.sha)\t\tMessage: \(.commit.message)\n---"') >> CHANGELOG.md

            # - name: Print commits of PR
            #   run: |
            #     echo "$(cat ./CHANGELOG.md)" 

                            
                

