name: compile PR changelog 

on:
    pull_request: 

jobs:
    # create a job called 'changelog' that prints all the commits messages in the PR
    changelog:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: print PR commits
              run: git log --pretty=format:"%s" ${{ github.event.before }}..${{ github.sha }}

            


