name: compile PR changelog 

on:
    pull_request: 

jobs:
    # create a job called 'changelog' that prints all the changes in the PR
    changelog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Print PR changes
              run: |
                git fetch origin ${{ github.event.pull_request.base.ref }}
                git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
            


