name: compile PR changelog 

on:
    pull_request: 

jobs:
    create-changlog:
        runs-on: ubuntu-latest
        steps:
            - name: count PR commits
              run: |
                echo "FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "$GITHUB_ENV"
                echo "[DEBUG] depth is: $FETCH_DEPTH"

            - name: checkout repo
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.head.ref }}
                fetch-depth: ${{ env.FETCH_DEPTH }}
        
            - name: print changelog
              run: git log --oneline --graph
                
                

