name: hello world

on: push

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: check tooling
          run: | 
            which az
            echo "az version: $(az version)"
        
